version: "3.4"

services:
  roomatematching-db:
    image: roomatematching-database
    build:
      context: ./Database
      dockerfile: Dockerfile
    ports:
      - 3306:3306

  roomatematching-server:
    image: roomatematching-backend
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - 3000:30000
